server:
  port: 8888
spring:
  application:
    name: nacos-config-import-example
  cloud:
    nacos:
      config:
        name: test.yml
        file-extension: yml
        group: DEFAULT_GROUP
        server-addr: localhost:8848
  config:
    import:
      - optional:nacos:/
      - optional:nacos:/group_02
      - optional:nacos:group_03/test01.yml
      - optional:nacos:group_04/test02.yml?refreshEnabled=false
